### ISSUE TITLE
Applying the patch always gives the "Trial" state no matter what I do

### ISSUE THREAD

**Issue by V952** [icegull/TabsStudioExplode#1]
I'm using the latest MSVS 2022 Community and every time I install the patch it still thinks I'm in a trial phase. I've got no idea what I'm doing wrong. I have both tried fresh releases from github and patching it myself from scratch. Tried different PCs. In all the cases it just gives me the 30 day trial and stops working afterwards. Is it possible they have changed the authorization mechanism or am I doing it wrong? Please tell me what other details do I need to provide.

**Comment by icegull** [comment]
After you replace the patch, you need to open the "About" of the TabsStudio from VS2022 toolbar, and input any name to register.

**Comment by V952** [comment]
Oh well, that was pretty retarded of me to not try that in the first place, thanks, works like a charm now

**Comment by icegull** [comment]
My bad. I should wirte this in the md. Anyway enjoy it!
